spring.application.name=IRCSL_Tracking

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://ircsldb:ircsldb@ircsldb.hvc95no.mongodb.net/ircsl_db?appName=ircsldb

# Server Port
server.port=8080

# For Email Notifications
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=harinins2001@gmail.com
spring.mail.password=xlfv hwzb nsnp dntx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
